name: Deploy to Vercel and Heroku

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
      runs-on: ubuntu-latest
      steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install Node for frontend
        uses: actions/setup-node@v3
        with:
    node-version: '18'
      - name: Install frontend dependencies
        run: |
          if [ -d "frontend" ]; then
            cd frontend
            npm install
          fi

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v20
   ##     if: ${{ secrets.VERCEL_TOKEN != '' }}
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_TEAM_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: ./frontend
          vercel-args: '--prod'

      - name: Deploy backend to Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git remote add heroku https://heroku:${HEROKU_API_KEY}@git.heroku.com/${HEROKU_APP_NAME}.git || true
          if [ -d "backend" ]; then
            git subtree push --prefix backend heroku main
          fi
